name: "Flake.lock: update all Nix dependencies"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 4 1 * *" # At 04:00 on day-of-month 1. – https://crontab.guru/#0_4_1_*_*

jobs:
  nix-flake-update:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update all Nix flake inputs" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
