general {
  after_sleep_cmd=hyprctl dispatch dpms on
  ignore_dbus_inhibit=false
  lock_cmd=wpctl set-mute @DEFAULT_AUDIO_SINK@ 1 && hyprlock
}

listener {
  timeout=20
  on-timeout=brightnessctl -d asus::kbd_backlight -s set 0%
  on-resume=brightnessctl -d asus::kbd_backlight -r
}

listener {
  on-timeout=wpctl set-mute @DEFAULT_AUDIO_SINK@ 1 && hyprlock
  timeout=900
}

listener {
  on-resume=hyprctl dispatch dpms on
  on-timeout=hyprctl dispatch dpms off
  timeout=1200
}
